/**
 * ============================================================================
 *  BBMOON PUNTADAS — Carga inicial de insumos
 * ============================================================================
 *  Archivo OPCIONAL. Pegalo como un segundo archivo dentro del mismo proyecto
 *  de Apps Script (botón + junto a "Archivos" -> Secuencia de comandos) y
 *  ejecutá UNA VEZ la función `cargarInsumosIniciales`.
 *
 *  Carga 48 insumos reales en la hoja Insumos_Stock.
 *  Si un código ya existe, actualiza esa fila en vez de duplicarla.
 * ============================================================================
 */

var INSUMOS_INICIALES = [
  {"codigo": "HIL-001", "categoria": "Hilos", "nombre": "Cono hilo poliéster 2000 yardas", "descripcion": "Hilo de coser poliéster para máquina recta, cono x2000 yd", "unidad_medida": "cono", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 2200, "margen_porcentaje": 60, "precio_venta_unitario": 3500, "proveedor": "Casa Jorge / Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Colores surtidos. Uso general en costura"},
  {"codigo": "HIL-002", "categoria": "Hilos", "nombre": "Hilo poliéster overlock 5000 m", "descripcion": "Cono grande para overlock/collareta", "unidad_medida": "cono", "cantidad_stock": 24, "stock_minimo": 6, "costo_unitario": 3800, "margen_porcentaje": 55, "precio_venta_unitario": 5900, "proveedor": "Mercería del Litoral", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Rinde mucho, ideal terminaciones"},
  {"codigo": "HIL-003", "categoria": "Hilos", "nombre": "Hilo algodón nº40 bobina", "descripcion": "Hilo de algodón para costura fina y bordado a máquina", "unidad_medida": "bobina", "cantidad_stock": 30, "stock_minimo": 8, "costo_unitario": 1500, "margen_porcentaje": 60, "precio_venta_unitario": 2400, "proveedor": "Addoumie Labath", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Para telas naturales"},
  {"codigo": "HIL-004", "categoria": "Hilos", "nombre": "Hilo encerado", "descripcion": "Hilo encerado para cuero y marroquinería", "unidad_medida": "rollo", "cantidad_stock": 12, "stock_minimo": 3, "costo_unitario": 2900, "margen_porcentaje": 65, "precio_venta_unitario": 4800, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Costura de cuero / apliques"},
  {"codigo": "HIL-005", "categoria": "Hilos", "nombre": "Hilo elástico (shirr)", "descripcion": "Hilo elástico para fruncido y elastizado", "unidad_medida": "rollo", "cantidad_stock": 15, "stock_minimo": 4, "costo_unitario": 1200, "margen_porcentaje": 70, "precio_venta_unitario": 2050, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Fruncidos, puños"},
  {"codigo": "HIL-006", "categoria": "Hilos", "nombre": "Hilo para bordar Mouline x12", "descripcion": "Madejas de hilo mouline para bordado a mano, pack x12 de 8m", "unidad_medida": "pack", "cantidad_stock": 20, "stock_minimo": 5, "costo_unitario": 3200, "margen_porcentaje": 55, "precio_venta_unitario": 4950, "proveedor": "Abrotex / La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Bordado y punto cruz"},
  {"codigo": "CIE-001", "categoria": "Cierres", "nombre": "Cierre común nº3 fijo 15 cm", "descripcion": "Cierre de poliéster nº3 fijo, 15 cm", "unidad_medida": "unidad", "cantidad_stock": 100, "stock_minimo": 25, "costo_unitario": 380, "margen_porcentaje": 80, "precio_venta_unitario": 700, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Prendas livianas, bolsillos"},
  {"codigo": "CIE-002", "categoria": "Cierres", "nombre": "Cierre común nº3 fijo 20 cm", "descripcion": "Cierre de poliéster nº3 fijo, 20 cm", "unidad_medida": "unidad", "cantidad_stock": 100, "stock_minimo": 25, "costo_unitario": 450, "margen_porcentaje": 80, "precio_venta_unitario": 800, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Pantalón, pollera"},
  {"codigo": "CIE-003", "categoria": "Cierres", "nombre": "Cierre invisible 30 cm", "descripcion": "Cierre invisible para vestidos y polleras, 30 cm", "unidad_medida": "unidad", "cantidad_stock": 80, "stock_minimo": 20, "costo_unitario": 620, "margen_porcentaje": 80, "precio_venta_unitario": 1100, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Terminación oculta"},
  {"codigo": "CIE-004", "categoria": "Cierres", "nombre": "Cierre invisible 50 cm", "descripcion": "Cierre invisible para vestidos, 50 cm", "unidad_medida": "unidad", "cantidad_stock": 60, "stock_minimo": 15, "costo_unitario": 950, "margen_porcentaje": 75, "precio_venta_unitario": 1650, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Vestidos largos"},
  {"codigo": "CIE-005", "categoria": "Cierres", "nombre": "Cierre YKK nº5 desmontable 70 cm", "descripcion": "Cierre YKK poliéster reforzado desmontable, 70 cm", "unidad_medida": "unidad", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 1233, "margen_porcentaje": 65, "precio_venta_unitario": 2050, "proveedor": "Casa Jorge (YKK)", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Camperas y abrigos"},
  {"codigo": "CIE-006", "categoria": "Cierres", "nombre": "Cierre YKK doble camino nº5 90 cm", "descripcion": "Cierre YKK doble carro reforzado, 90 cm", "unidad_medida": "unidad", "cantidad_stock": 25, "stock_minimo": 6, "costo_unitario": 3981, "margen_porcentaje": 55, "precio_venta_unitario": 6150, "proveedor": "Casa Jorge (YKK)", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Camperas largas, bolsos"},
  {"codigo": "CIE-007", "categoria": "Cierres", "nombre": "Cierre metálico nº5 18 cm", "descripcion": "Cierre de metal fijo nº5, 18 cm", "unidad_medida": "unidad", "cantidad_stock": 50, "stock_minimo": 12, "costo_unitario": 780, "margen_porcentaje": 75, "precio_venta_unitario": 1350, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Jean, prendas de trabajo"},
  {"codigo": "CIE-008", "categoria": "Cierres", "nombre": "Cierre por metro nº5 + carros", "descripcion": "Cadena de cierre poliéster nº5 por metro (se corta a medida)", "unidad_medida": "metro", "cantidad_stock": 30, "stock_minimo": 8, "costo_unitario": 900, "margen_porcentaje": 70, "precio_venta_unitario": 1550, "proveedor": "Casa Jorge (YKK)", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "A medida. Requiere carros"},
  {"codigo": "BOT-001", "categoria": "Botones", "nombre": "Botón camisa 4 agujeros 11 mm", "descripcion": "Botón plástico blanco 4 agujeros, 11 mm", "unidad_medida": "unidad", "cantidad_stock": 500, "stock_minimo": 100, "costo_unitario": 45, "margen_porcentaje": 100, "precio_venta_unitario": 100, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Camisería"},
  {"codigo": "BOT-002", "categoria": "Botones", "nombre": "Botón sastre 20 mm", "descripcion": "Botón para saco/blazer, 20 mm", "unidad_medida": "unidad", "cantidad_stock": 200, "stock_minimo": 40, "costo_unitario": 130, "margen_porcentaje": 90, "precio_venta_unitario": 250, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Sastrería"},
  {"codigo": "BOT-003", "categoria": "Botones", "nombre": "Botón jean con remache", "descripcion": "Botón metálico para jean a golpe, con remache", "unidad_medida": "juego", "cantidad_stock": 150, "stock_minimo": 30, "costo_unitario": 210, "margen_porcentaje": 85, "precio_venta_unitario": 400, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Requiere matriz/prensa"},
  {"codigo": "BOT-004", "categoria": "Botones", "nombre": "Broche a presión metálico 12 mm", "descripcion": "Broche tipo abrochador metálico, 12 mm", "unidad_medida": "juego", "cantidad_stock": 200, "stock_minimo": 40, "costo_unitario": 95, "margen_porcentaje": 90, "precio_venta_unitario": 200, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Ropa de bebé, camisas"},
  {"codigo": "BOT-005", "categoria": "Botones", "nombre": "Gancho y tanca (corchete)", "descripcion": "Ganchito y ojal de metal para pretinas", "unidad_medida": "juego", "cantidad_stock": 300, "stock_minimo": 60, "costo_unitario": 60, "margen_porcentaje": 100, "precio_venta_unitario": 100, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Pretinas de pantalón"},
  {"codigo": "BOT-006", "categoria": "Botones", "nombre": "Botón forrable con hormilla", "descripcion": "Botón para forrar con tela, con hormilla metálica", "unidad_medida": "unidad", "cantidad_stock": 120, "stock_minimo": 25, "costo_unitario": 110, "margen_porcentaje": 90, "precio_venta_unitario": 200, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Botón al tono de la prenda"},
  {"codigo": "ELA-001", "categoria": "Elásticos", "nombre": "Elástico plano 20 mm", "descripcion": "Elástico blanco tejido, ancho 20 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 100, "stock_minimo": 20, "costo_unitario": 320, "margen_porcentaje": 80, "precio_venta_unitario": 600, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Cinturas, puños"},
  {"codigo": "ELA-002", "categoria": "Elásticos", "nombre": "Elástico plano 40 mm", "descripcion": "Elástico blanco ancho 40 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 80, "stock_minimo": 20, "costo_unitario": 520, "margen_porcentaje": 75, "precio_venta_unitario": 900, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Cinturas anchas"},
  {"codigo": "ELA-003", "categoria": "Elásticos", "nombre": "Elástico redondo (cordón)", "descripcion": "Elástico redondo fino, por metro", "unidad_medida": "metro", "cantidad_stock": 60, "stock_minimo": 15, "costo_unitario": 180, "margen_porcentaje": 90, "precio_venta_unitario": 350, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Barbijos, ajustes"},
  {"codigo": "ELA-004", "categoria": "Elásticos", "nombre": "Elástico para corsetería", "descripcion": "Elástico decorado para ropa interior/corsetería", "unidad_medida": "metro", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 640, "margen_porcentaje": 70, "precio_venta_unitario": 1100, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Lencería"},
  {"codigo": "CIN-001", "categoria": "Cintas", "nombre": "Cinta de raso 10 mm", "descripcion": "Cinta de raso doble faz, 10 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 100, "stock_minimo": 20, "costo_unitario": 140, "margen_porcentaje": 100, "precio_venta_unitario": 300, "proveedor": "Mercería Caseros", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Moños, terminación"},
  {"codigo": "CIN-002", "categoria": "Cintas", "nombre": "Cinta de raso 25 mm", "descripcion": "Cinta de raso doble faz, 25 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 80, "stock_minimo": 20, "costo_unitario": 260, "margen_porcentaje": 90, "precio_venta_unitario": 500, "proveedor": "Mercería Caseros", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Decoración"},
  {"codigo": "CIN-003", "categoria": "Cintas", "nombre": "Cinta bies algodón 18 mm", "descripcion": "Bies de algodón para ribetear, 18 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 120, "stock_minimo": 30, "costo_unitario": 190, "margen_porcentaje": 90, "precio_venta_unitario": 350, "proveedor": "Addoumie Labath", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Terminación de bordes"},
  {"codigo": "CIN-004", "categoria": "Cintas", "nombre": "Cinta mochilera / correa 25 mm", "descripcion": "Cinta de polipropileno tipo correa, 25 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 60, "stock_minimo": 15, "costo_unitario": 300, "margen_porcentaje": 85, "precio_venta_unitario": 550, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Bolsos, mochilas"},
  {"codigo": "CIN-005", "categoria": "Cintas", "nombre": "Puntilla / broderie 30 mm", "descripcion": "Puntilla de algodón bordada, por metro", "unidad_medida": "metro", "cantidad_stock": 50, "stock_minimo": 12, "costo_unitario": 450, "margen_porcentaje": 80, "precio_venta_unitario": 800, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Ropa de bebé, lencería"},
  {"codigo": "CIN-006", "categoria": "Cintas", "nombre": "Cinta bandera argentina 10 mm", "descripcion": "Cinta celeste y blanca, por metro", "unidad_medida": "metro", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 210, "margen_porcentaje": 90, "precio_venta_unitario": 400, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Escarapelas, colegial"},
  {"codigo": "AGU-001", "categoria": "Agujas", "nombre": "Agujas máquina recta 90/14 x10", "descripcion": "Blister x10 agujas para máquina familiar, 90/14", "unidad_medida": "blister", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 1400, "margen_porcentaje": 65, "precio_venta_unitario": 2300, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Telas medianas"},
  {"codigo": "AGU-002", "categoria": "Agujas", "nombre": "Agujas máquina overlock x10", "descripcion": "Blister x10 agujas para overlock", "unidad_medida": "blister", "cantidad_stock": 25, "stock_minimo": 6, "costo_unitario": 1800, "margen_porcentaje": 60, "precio_venta_unitario": 2900, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Terminaciones"},
  {"codigo": "AGU-003", "categoria": "Agujas", "nombre": "Agujas de mano surtidas x19", "descripcion": "Canasta x19 agujas de coser a mano + enhebrador", "unidad_medida": "pack", "cantidad_stock": 30, "stock_minimo": 8, "costo_unitario": 850, "margen_porcentaje": 70, "precio_venta_unitario": 1450, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Costura a mano"},
  {"codigo": "AGU-004", "categoria": "Agujas", "nombre": "Alfileres cabeza de color x100", "descripcion": "Caja x100 alfileres con cabeza plástica de color", "unidad_medida": "caja", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 1100, "margen_porcentaje": 70, "precio_venta_unitario": 1850, "proveedor": "Mercería Caseros", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Armado y prueba"},
  {"codigo": "AGU-005", "categoria": "Agujas", "nombre": "Alfileres de gancho (imperdibles)", "descripcion": "Alfileres de gancho surtidos", "unidad_medida": "docena", "cantidad_stock": 30, "stock_minimo": 8, "costo_unitario": 700, "margen_porcentaje": 80, "precio_venta_unitario": 1250, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Uso general"},
  {"codigo": "ENT-001", "categoria": "Entretelas", "nombre": "Entretela termoadhesiva liviana", "descripcion": "Entretela fusionable liviana, por metro (ancho 90 cm)", "unidad_medida": "metro", "cantidad_stock": 50, "stock_minimo": 12, "costo_unitario": 900, "margen_porcentaje": 75, "precio_venta_unitario": 1600, "proveedor": "Addoumie Labath", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Cuellos, puños, camisería"},
  {"codigo": "ENT-002", "categoria": "Entretelas", "nombre": "Entretela termoadhesiva rígida", "descripcion": "Entretela fusionable rígida para cinturas y viseras, por metro", "unidad_medida": "metro", "cantidad_stock": 30, "stock_minimo": 8, "costo_unitario": 1300, "margen_porcentaje": 70, "precio_venta_unitario": 2200, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Pretinas, sombreros"},
  {"codigo": "ENT-003", "categoria": "Avíos", "nombre": "Hombreras raglán par", "descripcion": "Par de hombreras forradas raglán", "unidad_medida": "par", "cantidad_stock": 40, "stock_minimo": 10, "costo_unitario": 650, "margen_porcentaje": 80, "precio_venta_unitario": 1150, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Sastrería, blazers"},
  {"codigo": "ENT-004", "categoria": "Avíos", "nombre": "Cinta corsetera (ballena)", "descripcion": "Cinta corsetera con ballenas, por metro", "unidad_medida": "metro", "cantidad_stock": 20, "stock_minimo": 5, "costo_unitario": 1100, "margen_porcentaje": 70, "precio_venta_unitario": 1850, "proveedor": "Costuras Mayorista", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Corsetería, vestidos"},
  {"codigo": "ENT-005", "categoria": "Avíos", "nombre": "Velcro (abrojo) 20 mm", "descripcion": "Cinta de abrojo hembra+macho 20 mm, por metro", "unidad_medida": "metro", "cantidad_stock": 50, "stock_minimo": 12, "costo_unitario": 520, "margen_porcentaje": 80, "precio_venta_unitario": 950, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Cierres rápidos, calzado"},
  {"codigo": "HER-001", "categoria": "Herramientas", "nombre": "Tijera de sastre 8\"", "descripcion": "Tijera de costura profesional 8 pulgadas", "unidad_medida": "unidad", "cantidad_stock": 8, "stock_minimo": 2, "costo_unitario": 12500, "margen_porcentaje": 45, "precio_venta_unitario": 18100, "proveedor": "Tijeras Mundial", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Corte de tela. Bien de inversión"},
  {"codigo": "HER-002", "categoria": "Herramientas", "nombre": "Tijera de bordar / puntas finas", "descripcion": "Tijera pequeña para hilos y terminaciones", "unidad_medida": "unidad", "cantidad_stock": 12, "stock_minimo": 3, "costo_unitario": 3500, "margen_porcentaje": 55, "precio_venta_unitario": 5400, "proveedor": "Tijeras Mundial", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Cortar hilos, deshilar"},
  {"codigo": "HER-003", "categoria": "Herramientas", "nombre": "Centímetro (cinta métrica) x1", "descripcion": "Cinta métrica de modista 150 cm", "unidad_medida": "unidad", "cantidad_stock": 20, "stock_minimo": 5, "costo_unitario": 900, "margen_porcentaje": 80, "precio_venta_unitario": 1600, "proveedor": "La Paloma", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Toma de medidas"},
  {"codigo": "HER-004", "categoria": "Herramientas", "nombre": "Descosedor", "descripcion": "Descosedor con protector", "unidad_medida": "unidad", "cantidad_stock": 15, "stock_minimo": 4, "costo_unitario": 650, "margen_porcentaje": 85, "precio_venta_unitario": 1200, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Corregir costuras"},
  {"codigo": "HER-005", "categoria": "Herramientas", "nombre": "Jaboncillo / tiza de sastre x4", "descripcion": "Tizas de sastre para marcar, pack x4", "unidad_medida": "pack", "cantidad_stock": 25, "stock_minimo": 6, "costo_unitario": 800, "margen_porcentaje": 80, "precio_venta_unitario": 1450, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Marcado de moldes"},
  {"codigo": "HER-006", "categoria": "Herramientas", "nombre": "Aceite para máquina de coser", "descripcion": "Aceite lubricante para máquina, 125 ml", "unidad_medida": "unidad", "cantidad_stock": 20, "stock_minimo": 5, "costo_unitario": 1900, "margen_porcentaje": 70, "precio_venta_unitario": 3250, "proveedor": "Casa Jorge", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Mantenimiento de máquina"},
  {"codigo": "HER-007", "categoria": "Herramientas", "nombre": "Anilina para teñir x20g", "descripcion": "Anilina Colibrí para fibras naturales, sobre x20 g", "unidad_medida": "sobre", "cantidad_stock": 30, "stock_minimo": 8, "costo_unitario": 950, "margen_porcentaje": 80, "precio_venta_unitario": 1700, "proveedor": "Merceril", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Teñido de telas"},
  {"codigo": "HER-008", "categoria": "Herramientas", "nombre": "Marcador textil / lápiz para tela", "descripcion": "Lápiz o marcador que se borra para marcar telas", "unidad_medida": "unidad", "cantidad_stock": 20, "stock_minimo": 5, "costo_unitario": 1500, "margen_porcentaje": 75, "precio_venta_unitario": 2600, "proveedor": "Casa Nacho", "fecha_actualizacion_precio": "2026-07-12", "estado": "activo", "observaciones": "Marcado fino"}
];

/** Ejecutá esta función una sola vez desde el editor. */
function cargarInsumosIniciales() {
  var r = importInsumos({ insumos: JSON.parse(JSON.stringify(INSUMOS_INICIALES)) });
  Logger.log('Insumos creados: ' + r.creados + ' | actualizados: ' + r.actualizados);
  return r;
}

/** Borra todo lo que haya y carga la lista limpia. Usar con cuidado. */
function reemplazarInsumosPorLaListaInicial() {
  var r = importInsumos({ insumos: JSON.parse(JSON.stringify(INSUMOS_INICIALES)), modo: 'reemplazar' });
  Logger.log('Insumos cargados: ' + r.total);
  return r;
}
