'use strict';
var C=window.BBMOONCore;
var app=document.getElementById('app'),tabbar=document.getElementById('tabbar'),modal=document.getElementById('modal');
var API_KEY='bbmoon_api_url',TOKEN_LOCAL='bbmoon_token_local',TOKEN_SESSION='bbmoon_token_session';
var STATE={api:localStorage.getItem(API_KEY)||'',token:sessionStorage.getItem(TOKEN_SESSION)||localStorage.getItem(TOKEN_LOCAL)||'',rememberToken:!!localStorage.getItem(TOKEN_LOCAL),config:{},insumos:[],clientes:[],presupuestos:[],trabajos:[],caja:[],agenda:[],kpis:{},view:'dashboard',quoteDraft:null};
var PROVINCIAS=['Buenos Aires','CABA','Catamarca','Chaco','Chubut','Cordoba','Corrientes','Entre Rios','Formosa','Jujuy','La Pampa','La Rioja','Mendoza','Misiones','Neuquen','Rio Negro','Salta','San Juan','San Luis','Santa Cruz','Santa Fe','Santiago del Estero','Tierra del Fuego','Tucuman'];
var MEDIOS=['Efectivo','Transferencia','Mercado Pago','Debito','Credito','Otro'];
function esc(v){return String(v===undefined||v===null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function money(v){return C.money(v,'$');}
function fmtDate(v){var d=C.parseLocalDate(v);return d?String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear():'—';}
function toast(msg,kind){var el=document.getElementById('toast');el.textContent=msg;el.className='toast show '+(kind||'');clearTimeout(toast._t);toast._t=setTimeout(function(){el.className='toast';},2800);}
function loading(msg){app.innerHTML='<div class="loader">'+esc(msg||'Cargando…')+'</div>';}
function api(action,payload){
  if(!STATE.api||!STATE.token)return Promise.reject(new Error('Falta iniciar sesion.'));
  return fetch(STATE.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:action,payload:payload||{},token:STATE.token})})
    .then(function(r){return r.json();}).then(function(res){
      if(!res.ok){var e=new Error(res.error||'Error del servidor');e.code=res.code||'';throw e;}return res.data;
    }).catch(function(err){
      if(err.code==='SESSION_INVALID'){sessionStorage.removeItem(TOKEN_SESSION);localStorage.removeItem(TOKEN_LOCAL);STATE.token='';}
      throw err;
    });
}
function top(title,sub,back){return '<div class="topbar">'+(back?'<button class="iconbtn" onclick="go(\''+esc(back)+'\')">‹</button>':'<img class="logo" src="assets/logo_cuadrado.png" alt="BBMOON">')+'<div><h1>'+esc(title)+'</h1>'+(sub?'<div class="sub">'+esc(sub)+'</div>':'')+'</div><div class="spacer"></div><button class="iconbtn" onclick="go(\'config\')">⚙️</button></div>';}
function cardButton(icon,title,sub,view,primary){return '<button class="quick '+(primary?'primary':'')+'" onclick="go(\''+view+'\')"><span class="emoji">'+icon+'</span><strong>'+esc(title)+'</strong><span class="meta">'+esc(sub||'')+'</span></button>';}
function field(label,id,val,type,placeholder){var vv=(val===undefined||val===null)?'':val;return '<div class="field"><label for="'+id+'">'+esc(label)+'</label><input class="input" id="'+id+'" type="'+(type||'text')+'" value="'+esc(vv)+'" placeholder="'+esc(placeholder||'')+'"></div>';}
function textarea(label,id,val,placeholder){return '<div class="field"><label for="'+id+'">'+esc(label)+'</label><textarea class="textarea" id="'+id+'" placeholder="'+esc(placeholder||'')+'">'+esc(val||'')+'</textarea></div>';}
function select(label,id,options,val){return '<div class="field"><label for="'+id+'">'+esc(label)+'</label><select class="select" id="'+id+'"><option value="">—</option>'+options.map(function(o){var ov=typeof o==='object'?o.value:o,ol=typeof o==='object'?o.label:o;return '<option value="'+esc(ov)+'" '+(String(ov)===String(val)?'selected':'')+'>'+esc(ol)+'</option>';}).join('')+'</select></div>';}
function openModal(title,html){modal.innerHTML='<div class="overlay" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+esc(title)+'</h2><button class="iconbtn" onclick="closeModal()">✕</button></div>'+html+'</div></div>';}
function closeModal(){modal.innerHTML='';}
window.closeModal=closeModal;
function setTab(){var tabs=[['dashboard','🏠','Inicio'],['presupuestos','📄','Presup.'],['clientes','👥','Clientes'],['trabajos','✂️','Trabajos'],['gestion','🧰','Gestion']];tabbar.innerHTML='<div class="tabbar"><div class="inner">'+tabs.map(function(t){return '<button class="'+(STATE.view===t[0]?'active':'')+'" onclick="go(\''+t[0]+'\')"><span>'+t[1]+'</span>'+t[2]+'</button>';}).join('')+'</div></div>';}
function handleError(err){closeModal();toast(err&&err.message?err.message:'Error','err');if(!STATE.token)renderSetup(err&&err.message);}
function registerSW(){if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(function(){});}

function renderSetup(err){tabbar.innerHTML='';app.innerHTML='<div class="setup"><img src="assets/logo_cuadrado.png" alt="BBMOON"><h1>BBMOON PUNTADAS</h1><p>Conecta la planilla e inicia sesion con el PIN generado por <b>configurarAcceso()</b> en Apps Script.</p>'+(err?'<div class="warning">'+esc(err)+'</div>':'')+'<div class="card">'+field('URL del Web App','setup-api',STATE.api,'url','https://script.google.com/macros/s/.../exec')+field('PIN de acceso','setup-pin','','password','8 digitos')+'<label class="check"><input type="checkbox" id="setup-remember" '+(STATE.rememberToken?'checked':'')+'> Recordar sesion en este dispositivo</label><div style="height:12px"></div><button class="btn block" onclick="saveSetup()">Iniciar sesion</button></div><div class="hint" style="text-align:center">El PIN se usa solo para iniciar sesion. La app guarda un token revocable, no el PIN.</div></div>';}
window.saveSetup=function(){var url=document.getElementById('setup-api').value.trim(),pin=document.getElementById('setup-pin').value.trim(),remember=document.getElementById('setup-remember').checked;if(!/^https:\/\/script\.google\.com\/.+\/exec$/.test(url)){toast('Revisa la URL /exec','err');return;}if(!/^\d{8}$/.test(pin)){toast('El PIN debe tener 8 digitos','err');return;}STATE.api=url;STATE.rememberToken=remember;localStorage.setItem(API_KEY,url);loading('Iniciando sesion…');fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'login',pin:pin,payload:{}})}).then(function(r){return r.json();}).then(function(res){if(!res.ok)throw new Error(res.error||'No se pudo iniciar sesion');STATE.token=res.data.token;sessionStorage.setItem(TOKEN_SESSION,STATE.token);if(remember)localStorage.setItem(TOKEN_LOCAL,STATE.token);else localStorage.removeItem(TOKEN_LOCAL);return boot();}).catch(handleError);};

function loadAll(){return Promise.all([api('getConfig'),api('listInsumos'),api('listClientes'),api('listPresupuestos'),api('listTrabajos'),api('listCaja'),api('listAgenda'),api('getKPIs')]).then(function(r){STATE.config=r[0]||{};STATE.insumos=r[1]||[];STATE.clientes=r[2]||[];STATE.presupuestos=r[3]||[];STATE.trabajos=r[4]||[];STATE.caja=r[5]||[];STATE.agenda=r[6]||[];STATE.kpis=r[7]||{};});}
function boot(){if(!STATE.api||!STATE.token){renderSetup();return;}loading('Sincronizando con Google Sheets…');loadAll().then(function(){registerSW();go('dashboard');}).catch(handleError);}
window.go=function(view,param){STATE.view=view;window.scrollTo(0,0);var fn={dashboard:renderDashboard,presupuestos:renderQuotes,clientes:renderClients,trabajos:renderWorks,gestion:renderManagement,insumos:renderStock,caja:renderCash,agenda:renderAgenda,metricas:renderMetrics,config:renderConfig,quote:renderQuoteEditor,client:renderClientDetail,work:renderWorkDetail}[view]||renderDashboard;fn(param);setTab();};

function renderDashboard(){var k=STATE.kpis||{},name=STATE.config.nombre_negocio||'BBMOON PUNTADAS';app.innerHTML=top(name,'Panel del atelier')+'<div class="view"><div class="quick-grid">'+cardButton('✚','Nuevo presupuesto','Armar y exportar PDF','quote',true)+cardButton('💵','Caja','Ingresos y egresos','caja')+cardButton('📆','Agenda','Pruebas y entregas','agenda')+cardButton('🧵','Stock','Movimientos e inventario','insumos')+'</div><div class="section-title">Resumen del mes</div><div class="kpis">'+kpi('Presupuestado',money(k.monto_presupuestado))+kpi('Vendido',money(k.total_vendido))+kpi('Cobrado',money(k.total_cobrado))+kpi('Pendiente',money(k.saldo_pendiente))+kpi('Egresos',money(k.egresos_caja))+kpi('Resultado caja',money(k.resultado_caja))+kpi('Ganancia estimada',money(k.ganancia_estimada))+kpi('Conversion',(k.tasa_conversion||0)+'%')+'</div>'+(k.insumos_bajo_stock?'<div class="section-title">Stock bajo</div><div class="card">'+(k.lista_bajo_stock||[]).slice(0,5).map(function(i){return '<div class="totalrow"><span>'+esc(i.nombre)+'</span><b>'+esc(i.stock)+' / '+esc(i.minimo)+'</b></div>';}).join('')+'<button class="btn secondary block" onclick="go(\'insumos\')">Ver stock</button></div>':'')+'<div class="section-title">Proximos 7 dias</div><div class="card">'+agendaMini(k.agenda_proxima||[])+'</div></div>';}
function kpi(label,value){return '<div class="kpi"><b>'+value+'</b><span>'+esc(label)+'</span></div>';}
function agendaMini(list){if(!list.length)return '<div class="empty">No hay eventos proximos.</div>';return list.map(function(e){return '<div class="list-item"><div class="main"><div class="title">'+esc(e.titulo)+'</div><div class="meta">'+fmtDate(e.fecha)+(e.hora?' · '+esc(e.hora):'')+' · '+esc(e.cliente_nombre||e.tipo||'')+'</div></div><span class="chip">'+esc(e.prioridad||'normal')+'</span></div>';}).join('');}

function renderManagement(){app.innerHTML=top('Gestion','Herramientas del negocio','dashboard')+'<div class="view"><div class="quick-grid">'+cardButton('🧵','Insumos y stock','Inventario y movimientos','insumos')+cardButton('💵','Caja','Ingresos, egresos y medios de pago','caja')+cardButton('📆','Agenda','Pruebas, compras y entregas','agenda')+cardButton('📊','Metricas','Ventas y rentabilidad','metricas')+cardButton('⚙️','Configuracion','Datos, costos y respaldo','config')+'</div></div>';}
